### ISSUE TITLE
Notion-Enhancer

### ISSUE THREAD

**Issue by UniqueYang** [puneetsl/lotion#31]
Hello, I found a customization tool for Notion's Windows client (https://www.notion.so/Notion-Enhancer-147abdd0b5ed47c9b472520f9ee212a4). Since Lotion is also encapsulated in Electron, I think it can also be used to beautify Lotion. 
But I don't know anything about Electron or CSS, I'm just a Linux desktop user.I still changed the style of Notion in version 0.02. By modifying /Lotion/resources/app/lib/preload.js, adding

```js
function userscript() {
    /* Style Injecting */
    var fs = require("fs");
    let css = fs.readFileSync("lotion/Lotion/resources/app/lib/userscript.css"); //will be replaced in python patcher
    let head, style;
    head = document.getElementsByTagName('head')[0];
    if (!head) { return; }
    style = document.createElement('style');
    style.type = 'text/css';
    style.innerHTML = css;
    head.appendChild(style);
    /* Style Injecting */
}
require('electron').remote.getGlobal('setTimeout')(() => {  userscript(); }, 100);
```

userscript.css

```css
[style^="font-weight:600"]
{
font-family: Arial, Helvetica, sans-serif;
}

.notion-sidebar-container
{
background-color: #fff!important;
}

.notion-code-block
  {
    background: #F8F8FF;
  }

/* To make cursor style as pointer when hover on scrollbar */
.notion-scroller {
    cursor: auto;
}
/* Scrollbar size */
::-webkit-scrollbar {
    width: 5px; /* To change vertical scrollbar width */
    height: 7px; /* To change horizontal scrollbar height */
}
/* Element where vertical and horizontal scrollbars converge */
::-webkit-scrollbar-corner{
    background-color: transparent;
}

/* Light Theme style for Scrollbars */
.notion-light-theme ::-webkit-scrollbar-thumb {
    border-radius: 5px;
    background-color: #afafaf;
}
.notion-light-theme ::-webkit-scrollbar-track {
    border-radius: 5px;
    background-color: #e4e4e4;
}
.notion-light-theme ::-webkit-scrollbar-thumb:hover{
    background: #969696;
}
/* Light Theme style for Scrollbars */


/* Dark Theme style for Scrollbars */
.notion-dark-theme ::-webkit-scrollbar-track {
    border-radius: 5px;
    background-color: #3d3d42;
}
.notion-dark-theme ::-webkit-scrollbar-thumb {
    border-radius: 5px;
    background-color: #5d5d5d;
}
.notion-dark-theme ::-webkit-scrollbar-thumb:hover{
    background: #868686;
}
/* Dark Theme style for Scrollbars */
```

But in the 0.03 version I can't restore this scene. Hope you can guide me
